if(NOT EXISTS "${INSTALL_SCRIPT}")
  message(FATAL_ERROR "provider install script is missing: ${INSTALL_SCRIPT}")
endif()

file(READ "${INSTALL_SCRIPT}" install_script_contents)
set(private_fragment "/${INSTALL_LIBDIR}/metaflux/providers/${LIBRARY_STEM}")
set(global_fragment "/${INSTALL_LIBDIR}/${LIBRARY_STEM}")
string(FIND "${install_script_contents}" "${private_fragment}" private_position)
string(FIND "${install_script_contents}" "${global_fragment}" global_position)
if(private_position EQUAL -1)
  message(FATAL_ERROR "${LIBRARY_STEM} is not installed below metaflux/providers")
endif()
if(NOT global_position EQUAL -1)
  message(FATAL_ERROR "${LIBRARY_STEM} is installed in the global vendor lookup directory")
endif()
