#!/usr/bin/env python3
"""Compose canonical guest PCI identity and vfio-user BAR fixtures.

The sole ownership chain is:

  contracts/protocol/transport/v1/schema/manifest.json
    -> transport.vfio-user.v0 (BAR/MSI-X/doorbell profile)
  contracts/protocol/transport/v1/schema/extensions/vroot/v1/manifest.json
    -> transport.vroot-profile.v1 (CI Type-0 VID/DID/class)

Consumers (metaflux_pci.ko, live vfio-user server, guest bring-up) must take
identity and BAR sizes from the generated header. Handwritten competing
constants are rejected by tools/test-pci-guest-profile.py.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any


class GeneratorError(ValueError):
    """Combined guest/server PCI fixture generation failed."""


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise GeneratorError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def repository_root(path: Path) -> Path:
    for parent in (path, *path.parents):
        if (parent / "contracts").is_dir() and (parent / "tools").is_dir():
            return parent
    raise GeneratorError(f"cannot locate repository root from {path}")


def compose(root: Path) -> dict[str, Any]:
    tools = root / "tools"
    vfio = load_module(tools / "validate-vfio-user-profile.py", "metaflux_vfio_user_profile")
    vroot = load_module(tools / "validate-vroot-profile.py", "metaflux_vroot_profile")

    transport_manifest = root / "contracts/protocol/transport/v1/schema/manifest.json"
    vroot_manifest = (
        root / "contracts/protocol/transport/v1/schema/extensions/vroot/v1/manifest.json"
    )
    try:
        bar_profile = vfio.validate(root, transport_manifest)
        identity_profile, _image, _writable = vroot.validate(root, vroot_manifest)
    except Exception as error:  # noqa: BLE001 - surface validator text
        raise GeneratorError(str(error)) from error

    identity = identity_profile.get("identity")
    if not isinstance(identity, dict):
        raise GeneratorError("vroot profile identity is required")
    vendor_id = identity.get("vendor_id")
    device_id = identity.get("device_id")
    class_code = identity.get("class_code")
    if vendor_id != 0x4D46 or device_id != 0x0001 or class_code != 0x120000:
        raise GeneratorError("composed guest PCI identity is not the CI Type-0 lock")

    bars = {item["index"]: item for item in bar_profile["bars"]}
    return {
        "vendor_id": int(vendor_id),
        "device_id": int(device_id),
        "class_code": int(class_code),
        "page_size": int(bar_profile["page_size"]),
        "bar0_offset": int(bars[0]["offset"]),
        "bar0_size": int(bars[0]["size"]),
        "bar2_offset": int(bars[2]["offset"]),
        "bar2_size": int(bars[2]["size"]),
        "bar4_offset": int(bars[4]["offset"]),
        "bar4_size": int(bars[4]["size"]),
        "msix_vectors": int(bar_profile["msix_vectors"]),
        "doorbell_width": int(bar_profile["doorbell_width"]),
        "vfio_profile_id": bar_profile["id"],
        "vroot_profile_id": identity_profile["id"],
    }


def header_text(fixture: dict[str, Any], *, kernel: bool = False) -> str:
    include = "#include <linux/types.h>" if kernel else "#include <stdint.h>"
    u32 = "u32" if kernel else "uint32_t"
    u64 = "u64" if kernel else "uint64_t"
    return f"""/* Generated by tools/generate-pci-guest-profile.py; do not edit. */
#ifndef METAFLUX_PCI_GUEST_GENERATED_PROFILE_H
#define METAFLUX_PCI_GUEST_GENERATED_PROFILE_H

{include}

/* CI Type-0 identity from the vroot profile import closure. */
#define MF_PCI_GUEST_VENDOR_ID 0x{fixture['vendor_id']:04x}U
#define MF_PCI_GUEST_DEVICE_ID 0x{fixture['device_id']:04x}U
#define MF_PCI_GUEST_CLASS_CODE 0x{fixture['class_code']:06x}U

/* Static BAR/MSI-X profile from transport.vfio-user.v0. */
#define MF_PCI_GUEST_PAGE_SIZE (({u64})({fixture['page_size']}ULL))
#define MF_PCI_GUEST_BAR0_OFFSET (({u64})({fixture['bar0_offset']}ULL))
#define MF_PCI_GUEST_BAR0_SIZE (({u64})({fixture['bar0_size']}ULL))
#define MF_PCI_GUEST_BAR2_OFFSET (({u64})({fixture['bar2_offset']}ULL))
#define MF_PCI_GUEST_BAR2_SIZE (({u64})({fixture['bar2_size']}ULL))
#define MF_PCI_GUEST_BAR4_OFFSET (({u64})({fixture['bar4_offset']}ULL))
#define MF_PCI_GUEST_BAR4_SIZE (({u64})({fixture['bar4_size']}ULL))
#define MF_PCI_GUEST_MSIX_VECTORS (({u32})({fixture['msix_vectors']}U))
#define MF_PCI_GUEST_DOORBELL_WIDTH (({u32})({fixture['doorbell_width']}U))

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--generate-header", type=Path)
    parser.add_argument(
        "--kernel-header",
        action="store_true",
        help="Emit Linux-kernel type names (u32/u64) instead of stdint.",
    )
    arguments = parser.parse_args()
    root = (
        arguments.root.resolve()
        if arguments.root is not None
        else repository_root(Path(__file__).resolve())
    )
    try:
        fixture = compose(root)
        if arguments.generate_header is not None:
            output = arguments.generate_header.resolve()
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(
                header_text(fixture, kernel=arguments.kernel_header), encoding="utf-8"
            )
    except GeneratorError as error:
        print(f"pci-guest profile: invalid: {error}", file=sys.stderr)
        return 1
    print(
        "pci-guest profile: ok "
        f"({fixture['vfio_profile_id']}+{fixture['vroot_profile_id']} "
        f"vid=0x{fixture['vendor_id']:04x} did=0x{fixture['device_id']:04x} "
        f"class=0x{fixture['class_code']:06x})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
